### ISSUE TITLE
Using ALT-TAB to switch between IQSynth and other programs

### ISSUE THREAD

**Issue by jimruxton** [magdesign/IQSynth#17]
Is there a way to switch out of IQSynth while it is still running. Normally I can ALT-TAB between programs but IQSynth seems to grab all my keystrokes. I also tried starting IQSynth in a different workspace but again I can't seem to get to my other workspace as IQSynth appears to grab all keystrokes.

**Comment by johnday-github** [comment]
Ah, that may be a problem, I'll revisit the X11 code

**Comment by johnday-github** [comment]
@jimruxton This isn't going to play very nicely with whatever display manager is installed, I started with working in the display manager trying to use SDL and some other libraries some years ago but at the time it caused so many more problems then it solved, to the point I just couldn't get everything to play nicely. (although this is my first and only c++ program I've written) You can use other software at the moment if its not under the application. IQSynth uses a single on top window to keep it as fast as I could, switching contexts and sharing GL between windows, used to be very slow, and is not something I'm going to go back to review yet. I'm not sure at all how workspaces would play out.

I could look at trying to hide/show the application via Alt-TAB, but hiding it will also hide the output due to it being a single window. If I can get that to work, would that help?

**Comment by jimruxton** [comment]
@johnday-github  I am not clear what you mean by this:

> You can use other software at the moment if its not under the application. 

If I can't get out of IQSynth without killing it I'm not sure how I can use other applications under it?

>  I could look at trying to hide/show the application via Alt-TAB, but hiding it will also hide the output due to it being a single window. If I can get that to work, would that help?

Definitely this would be very helpful. I think anything that allows me to look at other running programs for example OBS while I am using IQSynth would be very useful. Thanks so much for investigating this.

On another point, if I have specific questions about using some aspect of the software, though it's not what I would call an "issue" what is the best way to approach that. Should I send an email or create a new issue. These are the kind of questions for example that would typically be asked in a  user forum. Really enjoying learning the software but a couple things I'm not quite getting :)

**Comment by johnday-github** [comment]
@jimruxton , I meant that for instance, I have other applications running to the side/below (on a higher resolution screen) or on another monitor, while IQSynth is running, and when you move the mouse outside of IQSynth it loses focus, but as you say you can't currently get to anything under it.

Cool, I'll see what I can do to allow you to pop-out of IQSynth, ie. ALT-TAB will de-focus the app and hide it, and hopefully I can pick up the refocus to show it.

You can email contact@iqsynth or there looks like there is a 'question' label on here. I don't mind either way at the moment. FYI: magdesign set this up.

**Comment by magdesign** [comment]
We could use the wiki section of this github repo to make a simple documentation.
And I tried to flag the issues to get a better overview.
@jimruxton Shall I add you to the contributer list, so you have full access to this repo?

**Comment by jimruxton** [comment]
@johnday-github 

> @jimruxton , I meant that for instance, I have other applications running to the side/below (on a higher resolution screen) or on another monitor, while IQSynth is running

Ok, I don't see anything on another monitor or below IQSynth when the program is running. It's as if it is in a Kiosk mode.

> Cool, I'll see what I can do to allow you to pop-out of IQSynth, ie. ALT-TAB will de-focus the app and hide it, and hopefully I can pick up the refocus to show it.

This would be great. Thank You :) 

I'll try the "question label" here rather than email. That way if anyone else has the same question they could find the answer here and not bother you with it.

**Comment by jimruxton** [comment]
@magdesign Sure that would be great if you could add me as a contributor to the repo. Thanks!

**Comment by johnday-github** [comment]
@jimruxton the switching focus coding is going to take a lot more research, it looks like I really have to talk to the display manager to get it to work. and that might include taking into account some reported quirks in gnome3 by the look of it (wouldn't be the first I've come across). I tried a few quick hacks to feel the water and nothing happened. I think this is going to be a slow burner I'm afraid.

**Comment by jimruxton** [comment]
Hey, no problem @johnday-github I really appreciate you trying. I'm sure you  have more pressing things to work on. Meanwhile @magdesign if you have ever come upon a way either using different workspaces or other methods of switching between IQSynth and other programs while IQSynth is running please let me know. My use case may be different than most using the software. I am using  OBS to stream the output of IQSynth so it would be nice to be able to look at that software as IQSynth is running. That said, I have managed fine as is so it would just be a bonus for me :)  .

**Comment by johnday-github** [comment]
Looking at this again now

**Comment by johnday-github** [comment]
Hi @jimruxton , see release v0.19.2

I could get the desktop manager (well, gnome) to respect the iconify request only if its in window mode.
So I've added a window mode option to the application. 

Find it in 'Configuration & Tools'->Configuration->Display. Save a changes and restart application.

This starts the app with window decorations which allows iconify/de-iconify actions, including using Alt-Tab.
Note: this does then off-set the app and output due to the window decorations.

I could do with working out how to include/set an application icon, but will leave that for now. 

Tell us if it works for you.

**Comment by jimruxton** [comment]
This is great John. It works for me. It would be nice not to have the Title Bar at the top of the output window but I guess it isn't possible in window mode. This makes it difficult to use during a performance but amazing during development of something. Thanks so much for adding this feature.

**Comment by johnday-github** [comment]
Cool, yep shame about not getting to work without the title bar, it seemed that what ever I tried, once I told the window manager not to draw decorations (ie title bar) it also stop responding to iconify requests/events. It might just be a gnome thing or I've still not quite got the setup/order correct (I did read and try quite a few different things). Anyway, thought this might help during setup.
I'll close this for now.

**Comment by johnday-github** [comment]
Hi @jimruxton, I had an idea about this yesterday, I was so close and I think I've managed to beat it into submission.

Try 0.19.4, I can use Alt-Tab even in border less mode!

Its a little bit of a work around under the bonnet but I can't see why it shouldn't also work for you. Let me know!

**Comment by jimruxton** [comment]
This is working perfectly. Soooo useful. Thanks for putting in all the effort on this. Hopefully others find this as useful as I do. You can firmly close this issue now!

**Comment by johnday-github** [comment]
:+1:
